{% set name = "robocorp-storage" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robocorp_storage-{{ version }}.tar.gz
  sha256: a410dda8b2bf82308458dbe94ac420dd92ab6cecce5e67bce69ac115a0b99294

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - requests >=2.28.2,<3.0.0
    - tenacity >=8.0.1,<9.0.0
    - typing-extensions >=4.5.0,<5.0.0

test:
  imports:
    - robocorp.storage
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robocorp/robo/
  summary: Robocorp Asset Storage library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
